// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: secrethub.proto

package io.secrethub.proto;

public final class SecretHub {
  private SecretHub() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ReadRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:secrethub.ReadRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string path = 1;</code>
     * @return The path.
     */
    java.lang.String getPath();
    /**
     * <code>string path = 1;</code>
     * @return The bytes for path.
     */
    com.google.protobuf.ByteString
        getPathBytes();
  }
  /**
   * Protobuf type {@code secrethub.ReadRequest}
   */
  public  static final class ReadRequest extends
      com.google.protobuf.GeneratedMessageLite<
          ReadRequest, ReadRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:secrethub.ReadRequest)
      ReadRequestOrBuilder {
    private ReadRequest() {
      path_ = "";
    }
    public static final int PATH_FIELD_NUMBER = 1;
    private java.lang.String path_;
    /**
     * <code>string path = 1;</code>
     * @return The path.
     */
    @java.lang.Override
    public java.lang.String getPath() {
      return path_;
    }
    /**
     * <code>string path = 1;</code>
     * @return The bytes for path.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPathBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(path_);
    }
    /**
     * <code>string path = 1;</code>
     * @param value The path to set.
     */
    private void setPath(
        java.lang.String value) {
      value.getClass();
  
      path_ = value;
    }
    /**
     * <code>string path = 1;</code>
     */
    private void clearPath() {
      
      path_ = getDefaultInstance().getPath();
    }
    /**
     * <code>string path = 1;</code>
     * @param value The bytes for path to set.
     */
    private void setPathBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      path_ = value.toStringUtf8();
      
    }

    public static io.secrethub.proto.SecretHub.ReadRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static io.secrethub.proto.SecretHub.ReadRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static io.secrethub.proto.SecretHub.ReadRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static io.secrethub.proto.SecretHub.ReadRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static io.secrethub.proto.SecretHub.ReadRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static io.secrethub.proto.SecretHub.ReadRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static io.secrethub.proto.SecretHub.ReadRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static io.secrethub.proto.SecretHub.ReadRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static io.secrethub.proto.SecretHub.ReadRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static io.secrethub.proto.SecretHub.ReadRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static io.secrethub.proto.SecretHub.ReadRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static io.secrethub.proto.SecretHub.ReadRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(io.secrethub.proto.SecretHub.ReadRequest prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code secrethub.ReadRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          io.secrethub.proto.SecretHub.ReadRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:secrethub.ReadRequest)
        io.secrethub.proto.SecretHub.ReadRequestOrBuilder {
      // Construct using io.secrethub.proto.SecretHub.ReadRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string path = 1;</code>
       * @return The path.
       */
      @java.lang.Override
      public java.lang.String getPath() {
        return instance.getPath();
      }
      /**
       * <code>string path = 1;</code>
       * @return The bytes for path.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPathBytes() {
        return instance.getPathBytes();
      }
      /**
       * <code>string path = 1;</code>
       * @param value The path to set.
       * @return This builder for chaining.
       */
      public Builder setPath(
          java.lang.String value) {
        copyOnWrite();
        instance.setPath(value);
        return this;
      }
      /**
       * <code>string path = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPath() {
        copyOnWrite();
        instance.clearPath();
        return this;
      }
      /**
       * <code>string path = 1;</code>
       * @param value The bytes for path to set.
       * @return This builder for chaining.
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPathBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:secrethub.ReadRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new io.secrethub.proto.SecretHub.ReadRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "path_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<io.secrethub.proto.SecretHub.ReadRequest> parser = PARSER;
          if (parser == null) {
            synchronized (io.secrethub.proto.SecretHub.ReadRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<io.secrethub.proto.SecretHub.ReadRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:secrethub.ReadRequest)
    private static final io.secrethub.proto.SecretHub.ReadRequest DEFAULT_INSTANCE;
    static {
      ReadRequest defaultInstance = new ReadRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ReadRequest.class, defaultInstance);
    }

    public static io.secrethub.proto.SecretHub.ReadRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ReadRequest> PARSER;

    public static com.google.protobuf.Parser<ReadRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ReadResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:secrethub.ReadResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.secrethub.Secret secret = 1;</code>
     * @return Whether the secret field is set.
     */
    boolean hasSecret();
    /**
     * <code>.secrethub.Secret secret = 1;</code>
     * @return The secret.
     */
    io.secrethub.proto.SecretHub.Secret getSecret();

    /**
     * <code>string error = 2;</code>
     * @return The error.
     */
    java.lang.String getError();
    /**
     * <code>string error = 2;</code>
     * @return The bytes for error.
     */
    com.google.protobuf.ByteString
        getErrorBytes();
  }
  /**
   * Protobuf type {@code secrethub.ReadResponse}
   */
  public  static final class ReadResponse extends
      com.google.protobuf.GeneratedMessageLite<
          ReadResponse, ReadResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:secrethub.ReadResponse)
      ReadResponseOrBuilder {
    private ReadResponse() {
      error_ = "";
    }
    public static final int SECRET_FIELD_NUMBER = 1;
    private io.secrethub.proto.SecretHub.Secret secret_;
    /**
     * <code>.secrethub.Secret secret = 1;</code>
     */
    @java.lang.Override
    public boolean hasSecret() {
      return secret_ != null;
    }
    /**
     * <code>.secrethub.Secret secret = 1;</code>
     */
    @java.lang.Override
    public io.secrethub.proto.SecretHub.Secret getSecret() {
      return secret_ == null ? io.secrethub.proto.SecretHub.Secret.getDefaultInstance() : secret_;
    }
    /**
     * <code>.secrethub.Secret secret = 1;</code>
     */
    private void setSecret(io.secrethub.proto.SecretHub.Secret value) {
      value.getClass();
  secret_ = value;
      
      }
    /**
     * <code>.secrethub.Secret secret = 1;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeSecret(io.secrethub.proto.SecretHub.Secret value) {
      value.getClass();
  if (secret_ != null &&
          secret_ != io.secrethub.proto.SecretHub.Secret.getDefaultInstance()) {
        secret_ =
          io.secrethub.proto.SecretHub.Secret.newBuilder(secret_).mergeFrom(value).buildPartial();
      } else {
        secret_ = value;
      }
      
    }
    /**
     * <code>.secrethub.Secret secret = 1;</code>
     */
    private void clearSecret() {  secret_ = null;
      
    }

    public static final int ERROR_FIELD_NUMBER = 2;
    private java.lang.String error_;
    /**
     * <code>string error = 2;</code>
     * @return The error.
     */
    @java.lang.Override
    public java.lang.String getError() {
      return error_;
    }
    /**
     * <code>string error = 2;</code>
     * @return The bytes for error.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getErrorBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(error_);
    }
    /**
     * <code>string error = 2;</code>
     * @param value The error to set.
     */
    private void setError(
        java.lang.String value) {
      value.getClass();
  
      error_ = value;
    }
    /**
     * <code>string error = 2;</code>
     */
    private void clearError() {
      
      error_ = getDefaultInstance().getError();
    }
    /**
     * <code>string error = 2;</code>
     * @param value The bytes for error to set.
     */
    private void setErrorBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      error_ = value.toStringUtf8();
      
    }

    public static io.secrethub.proto.SecretHub.ReadResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static io.secrethub.proto.SecretHub.ReadResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static io.secrethub.proto.SecretHub.ReadResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static io.secrethub.proto.SecretHub.ReadResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static io.secrethub.proto.SecretHub.ReadResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static io.secrethub.proto.SecretHub.ReadResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static io.secrethub.proto.SecretHub.ReadResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static io.secrethub.proto.SecretHub.ReadResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static io.secrethub.proto.SecretHub.ReadResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static io.secrethub.proto.SecretHub.ReadResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static io.secrethub.proto.SecretHub.ReadResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static io.secrethub.proto.SecretHub.ReadResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(io.secrethub.proto.SecretHub.ReadResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code secrethub.ReadResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          io.secrethub.proto.SecretHub.ReadResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:secrethub.ReadResponse)
        io.secrethub.proto.SecretHub.ReadResponseOrBuilder {
      // Construct using io.secrethub.proto.SecretHub.ReadResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.secrethub.Secret secret = 1;</code>
       */
      @java.lang.Override
      public boolean hasSecret() {
        return instance.hasSecret();
      }
      /**
       * <code>.secrethub.Secret secret = 1;</code>
       */
      @java.lang.Override
      public io.secrethub.proto.SecretHub.Secret getSecret() {
        return instance.getSecret();
      }
      /**
       * <code>.secrethub.Secret secret = 1;</code>
       */
      public Builder setSecret(io.secrethub.proto.SecretHub.Secret value) {
        copyOnWrite();
        instance.setSecret(value);
        return this;
        }
      /**
       * <code>.secrethub.Secret secret = 1;</code>
       */
      public Builder setSecret(
          io.secrethub.proto.SecretHub.Secret.Builder builderForValue) {
        copyOnWrite();
        instance.setSecret(builderForValue.build());
        return this;
      }
      /**
       * <code>.secrethub.Secret secret = 1;</code>
       */
      public Builder mergeSecret(io.secrethub.proto.SecretHub.Secret value) {
        copyOnWrite();
        instance.mergeSecret(value);
        return this;
      }
      /**
       * <code>.secrethub.Secret secret = 1;</code>
       */
      public Builder clearSecret() {  copyOnWrite();
        instance.clearSecret();
        return this;
      }

      /**
       * <code>string error = 2;</code>
       * @return The error.
       */
      @java.lang.Override
      public java.lang.String getError() {
        return instance.getError();
      }
      /**
       * <code>string error = 2;</code>
       * @return The bytes for error.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getErrorBytes() {
        return instance.getErrorBytes();
      }
      /**
       * <code>string error = 2;</code>
       * @param value The error to set.
       * @return This builder for chaining.
       */
      public Builder setError(
          java.lang.String value) {
        copyOnWrite();
        instance.setError(value);
        return this;
      }
      /**
       * <code>string error = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearError() {
        copyOnWrite();
        instance.clearError();
        return this;
      }
      /**
       * <code>string error = 2;</code>
       * @param value The bytes for error to set.
       * @return This builder for chaining.
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setErrorBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:secrethub.ReadResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new io.secrethub.proto.SecretHub.ReadResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "secret_",
              "error_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\t\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<io.secrethub.proto.SecretHub.ReadResponse> parser = PARSER;
          if (parser == null) {
            synchronized (io.secrethub.proto.SecretHub.ReadResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<io.secrethub.proto.SecretHub.ReadResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:secrethub.ReadResponse)
    private static final io.secrethub.proto.SecretHub.ReadResponse DEFAULT_INSTANCE;
    static {
      ReadResponse defaultInstance = new ReadResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ReadResponse.class, defaultInstance);
    }

    public static io.secrethub.proto.SecretHub.ReadResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ReadResponse> PARSER;

    public static com.google.protobuf.Parser<ReadResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SecretOrBuilder extends
      // @@protoc_insertion_point(interface_extends:secrethub.Secret)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string path = 1;</code>
     * @return The path.
     */
    java.lang.String getPath();
    /**
     * <code>string path = 1;</code>
     * @return The bytes for path.
     */
    com.google.protobuf.ByteString
        getPathBytes();

    /**
     * <code>int32 version = 2;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code secrethub.Secret}
   */
  public  static final class Secret extends
      com.google.protobuf.GeneratedMessageLite<
          Secret, Secret.Builder> implements
      // @@protoc_insertion_point(message_implements:secrethub.Secret)
      SecretOrBuilder {
    private Secret() {
      path_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int PATH_FIELD_NUMBER = 1;
    private java.lang.String path_;
    /**
     * <code>string path = 1;</code>
     * @return The path.
     */
    @java.lang.Override
    public java.lang.String getPath() {
      return path_;
    }
    /**
     * <code>string path = 1;</code>
     * @return The bytes for path.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPathBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(path_);
    }
    /**
     * <code>string path = 1;</code>
     * @param value The path to set.
     */
    private void setPath(
        java.lang.String value) {
      value.getClass();
  
      path_ = value;
    }
    /**
     * <code>string path = 1;</code>
     */
    private void clearPath() {
      
      path_ = getDefaultInstance().getPath();
    }
    /**
     * <code>string path = 1;</code>
     * @param value The bytes for path to set.
     */
    private void setPathBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      path_ = value.toStringUtf8();
      
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private int version_;
    /**
     * <code>int32 version = 2;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 2;</code>
     * @param value The version to set.
     */
    private void setVersion(int value) {
      
      version_ = value;
    }
    /**
     * <code>int32 version = 2;</code>
     */
    private void clearVersion() {
      
      version_ = 0;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>bytes data = 3;</code>
     * @param value The data to set.
     */
    private void setData(com.google.protobuf.ByteString value) {
      value.getClass();
  
      data_ = value;
    }
    /**
     * <code>bytes data = 3;</code>
     */
    private void clearData() {
      
      data_ = getDefaultInstance().getData();
    }

    public static io.secrethub.proto.SecretHub.Secret parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static io.secrethub.proto.SecretHub.Secret parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static io.secrethub.proto.SecretHub.Secret parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static io.secrethub.proto.SecretHub.Secret parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static io.secrethub.proto.SecretHub.Secret parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static io.secrethub.proto.SecretHub.Secret parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static io.secrethub.proto.SecretHub.Secret parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static io.secrethub.proto.SecretHub.Secret parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static io.secrethub.proto.SecretHub.Secret parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static io.secrethub.proto.SecretHub.Secret parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static io.secrethub.proto.SecretHub.Secret parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static io.secrethub.proto.SecretHub.Secret parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(io.secrethub.proto.SecretHub.Secret prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code secrethub.Secret}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          io.secrethub.proto.SecretHub.Secret, Builder> implements
        // @@protoc_insertion_point(builder_implements:secrethub.Secret)
        io.secrethub.proto.SecretHub.SecretOrBuilder {
      // Construct using io.secrethub.proto.SecretHub.Secret.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string path = 1;</code>
       * @return The path.
       */
      @java.lang.Override
      public java.lang.String getPath() {
        return instance.getPath();
      }
      /**
       * <code>string path = 1;</code>
       * @return The bytes for path.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPathBytes() {
        return instance.getPathBytes();
      }
      /**
       * <code>string path = 1;</code>
       * @param value The path to set.
       * @return This builder for chaining.
       */
      public Builder setPath(
          java.lang.String value) {
        copyOnWrite();
        instance.setPath(value);
        return this;
      }
      /**
       * <code>string path = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPath() {
        copyOnWrite();
        instance.clearPath();
        return this;
      }
      /**
       * <code>string path = 1;</code>
       * @param value The bytes for path to set.
       * @return This builder for chaining.
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPathBytes(value);
        return this;
      }

      /**
       * <code>int32 version = 2;</code>
       * @return The version.
       */
      @java.lang.Override
      public int getVersion() {
        return instance.getVersion();
      }
      /**
       * <code>int32 version = 2;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {
        copyOnWrite();
        instance.setVersion(value);
        return this;
      }
      /**
       * <code>int32 version = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        copyOnWrite();
        instance.clearVersion();
        return this;
      }

      /**
       * <code>bytes data = 3;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return instance.getData();
      }
      /**
       * <code>bytes data = 3;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setData(value);
        return this;
      }
      /**
       * <code>bytes data = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:secrethub.Secret)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new io.secrethub.proto.SecretHub.Secret();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "path_",
              "version_",
              "data_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0004" +
                "\u0003\n";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<io.secrethub.proto.SecretHub.Secret> parser = PARSER;
          if (parser == null) {
            synchronized (io.secrethub.proto.SecretHub.Secret.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<io.secrethub.proto.SecretHub.Secret>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:secrethub.Secret)
    private static final io.secrethub.proto.SecretHub.Secret DEFAULT_INSTANCE;
    static {
      Secret defaultInstance = new Secret();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Secret.class, defaultInstance);
    }

    public static io.secrethub.proto.SecretHub.Secret getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Secret> PARSER;

    public static com.google.protobuf.Parser<Secret> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
